### ISSUE TITLE
3D Consistency of RealEstate10K

### ISSUE THREAD

**Issue by 1ssb** [ayushtewari/DFM#14]
I have been trying to get a point cloud to check for the 3D consistency of the scenes developed in Real Estate sampling. It doesn't seem like they are 3D consistent for the experiments I performed. Could it be that there is some form of anisotropic scaling which might be happening to the pixel Nerf coordinate to world coordinate. Where could I be going wrong?

Note: I am trying alternative approaches.

**Comment by 1ssb** [comment]
A bit more evidence, to add to my understanding of the shortcoming of this model, already shared with the author @ayushtewari is this particular sample generated in the process.

https://github.com/ayushtewari/DFM/assets/40661648/d5224688-8198-4132-9ff2-91e60da7f838

Notice how the fireplace stretches as it rotates (immaterial of how rapidly the poses are changing) this drift should not be happening as per my understanding. Would really love to understand what is going wrong, or whether there is any mistake from my side. I can assure that I have changed nothing but the poses being loaded.

**Comment by 1ssb** [comment]
Update 2: This is to show that indeed my transformations are correct and something else is going wrong. Please find here two pairwise point clouds (30-31 and 42-43) and a point cloud between the 3rd and 30th. Please find the files here:

https://1drv.ms/f/s!AuTpPZap6gTYizMDG5Cq5llq9lej?e=3lObF3

**Comment by edwinseychelles** [comment]
Same here, did you find what could be going wrong? There does not seem to be any sources of anisotropic scaling.
