### ISSUE TITLE
How are you fetching the depth scale in CO3D but not in the RealEstate10K data?

### ISSUE THREAD

**Issue by 1ssb** [ayushtewari/DFM#15]
Same as title.

I am not being able to understand that if the scene scales are not provided nor computed how is RealEstate10K able to recognize the depth of the scene it's seeing in the NDC and if it didn't need it to begin with why does the CO3D data preparation need it.

Any explanation is helpful, thanks.

**Comment by edwinseychelles** [comment]
It isn't which is possibly the reason why RealEstate10K is not very consistent.

**Comment by 1ssb** [comment]
Its consistent as long as one follows re.indices.
