### ISSUE TITLE
Depth visualization looks strange

### ISSUE THREAD

**Issue by fzy139** [ayushtewari/DFM#3]
Hi,

Thanks for your excellent work.

I run the inference code on co3d hydrant following the instruction. The generated views look correct but the depth seems strange. Is that reasonable?

<img width="1301" alt="image" src="https://github.com/ayushtewari/DFM/assets/34181155/82288f97-f9e5-4a49-8093-0459177920a1">

**Comment by tianweiy** [comment]
fixed in [`862e9b3 `](https://github.com/ayushtewari/DFM/commit/862e9b338b169f59275ee7c07a54c6d95cd52435)

Thanks!

**Comment by fzy139** [comment]
So fast!! Thanks!
